INSERT INTO Department(DepName)VALUES ('Dep_name_0')
INSERT INTO Department(DepName)VALUES ('Dep_name_1')
INSERT INTO Department(DepName)VALUES ('Dep_name_2')
INSERT INTO Department(DepName)VALUES ('Dep_name_3')
INSERT INTO Department(DepName)VALUES ('Dep_name_4')
INSERT INTO Department(DepName)VALUES ('Dep_name_5')
INSERT INTO Department(DepName)VALUES ('Dep_name_6')